### ISSUE TITLE
2.9版本，使用clash.meta内核，对于hysteria格式无法解析

### ISSUE THREAD

**Issue by istek** [2dust/clashN#189]
在clash meta官方文档中，hysteria 格式如下

```
proxies:
  - name: "hysteria"
    type: hysteria
    server: server.com
    port: 443
    auth_str: yourpassword
    #obfs: yourpassword
    alpn:
      - h3  #1.13.2以上版本变更为数组
    protocol: udp          #支持udp/wechat-video/faketcp
    up: '30 Mbps'          #若不写单位，默认为Mbps
    down: '200 Mbps'       #若不写单位，默认为Mbps
    #sni: server.com
    #skip-cert-verify: false
    #recv_window_conn: 12582912
    #recv_window: 52428800
    #auth_str: "yubiyubi"
    #ca: "./my.ca"
    #ca_str: "xyz"
    #disable_mtu_discovery: false
```

alpn 自1.13.2 以后改为数组了， clashN无法识别， 如果使用 `alpn: h3` 虽然clashN能加载配置文件，但是无法使用。
