### ISSUE TITLE
有没有mixin更详细的使用方法？

### ISSUE THREAD

**Issue by Kam323** [2dust/clashN#303]
例如，怎样删除订阅中原有的所有proxy groups和rules？如何往自己建立的proxy group中添加proxy规则？（clash for windows的parsers功能是用cammands指令添加，目前使用没什么问题，我觉得可以参考）

本人不是程序员，不知道是否mixin只能使用JavaScript来实现对订阅配置的编辑，望指教，感谢！

**Comment by Kam323** [comment]
以下是我在clash for windows的parsers功能中使用的编辑方法，不知道用clashN的mixin功能如何实现？
[parsers.txt](https://github.com/2dust/clashN/files/13045297/parsers.txt)

**Comment by SinnoSong** [comment]
@Kam323 可以参考下我现在使用的，我没有删除原来的配置，只是添加新的。
```yaml
#
# 配置文件内容不会被修改，混合行为只会发生在内存中
#
# 注意下面缩进，请用支持yaml显示的编辑器打开
#
# 使用clash配置文件关键字则覆盖原配置
#
# removed-rules    循环匹配rules数组每行,符合则移除当前行 (此规则请放最前面)
#
# append-rules    数组合并至原配置rules数组后
# prepend-rules   数组合并至原配置rules数组前
# append-proxies      数组合并至原配置proxies数组后
# prepend-proxies     数组合并至原配置proxies数组前
# append-proxy-groups     数组合并至原配置proxy-groups数组后
# prepend-proxy-groups    数组合并至原配置proxy-groups数组前
# append-rule-providers     数组合并至原配置rule-providers数组后
# prepend-rule-providers    数组合并至原配置rule-providers数组前
#

dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
append-proxies:
  - {
      name: test,
      type: ss,
      server: ip,
      port: 端口,
      cipher: aes-256-cfb,
      password: password,
      udp: true,
    }
append-proxy-groups:
  - { name: "test", type: select, proxies: [test] }
prepend-rules:
  - "IP-CIDR,ip/24,test"
  - "DOMAIN-KEYWORD,domain,test"
```
